title: Seo Jin Jeong
theme: jekyll-theme-minimal
description: >-
  Here is my portfolio

# ▼▼▼ 여기에 이 코드를 추가하세요 ▼▼▼
header_pages:
  - README.md
  - projects.md     # qdd-actuator.md 대신 이걸로 변경 추천
  - about.md
# ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
